### ISSUE TITLE
在type: module Error: Dynamic require of "path" is not supported

### ISSUE THREAD

**Issue by LYlanfeng** [sxzz/unplugin-vue-define-options#1]
file:///D:/workspace/github/ly/node_modules/.pnpm/registry.npmmirror.com+unplugin-vue-define-options@0.1.2/node_modules/unplugin-vue-define-options/dist/chunk-WNNTV2HR.mjs:30
  throw new Error('Dynamic require of "' + x + '" is not supported');

**Comment by sxzz** [comment]
Please provide a minimum reproduction repo

**Comment by sxzz** [comment]
Please try `0.3.0`.

**Comment by LYlanfeng** [comment]
try 0.3.1 is ok
