### ISSUE TITLE
when i use this plugin , my .vue file output "Import in body of module; reorder to top  import/first"

### ISSUE THREAD

**Issue by 123slp** [sxzz/unplugin-vue-define-options#21]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/40046774/163724228-4f156d95-93cd-4dfd-86d2-81a4675c51fa.png">

**Comment by sxzz** [comment]
I don't think this is a problem with this plugin.
But if you provide a minimal reproduction repository, I can help you.
