### ISSUE TITLE
HMR update error when referencing imports

### ISSUE THREAD

**Issue by innocenzi** [sxzz/unplugin-vue-define-options#3]
Related to #2, I found how to consistently reproduce the issue I was talking about.

With the same repository as before (https://github.com/innocenzi/define-options-issue-2), you can simply start the dev server, open the page in your browser, and save `App.vue` to trigger an HMR update. It will trigger the following error:

![](https://i.imgur.com/N4Jlnmm.png)

After that, subsequent refreshes will all trigger the error. Restarting the server fixes them. Unfortunately I don't have enough Vite knowledge to understand where this issue comes from. I just know it's triggered there: https://github.com/sxzz/unplugin-vue-define-options/blob/main/src/index.ts#L40

**Comment by sxzz** [comment]
Could you please try latest version (now v0.2.2). I still can't reproduce this problem.

**Comment by innocenzi** [comment]
It appears that as of v0.2.2, the issue is gone! I'm very grateful for your help on this matter. Thank you ❤️

**Comment by sxzz** [comment]
Thanks for your feedback!
