### ISSUE TITLE
找不到名称“defineOptions”。

### ISSUE THREAD

**Issue by Greasen** [sxzz/unplugin-vue-define-options#31]
"vite": "^2.9.12",
"vue": "^3.2.37"

vite.config.ts:
import DefineOptions from 'unplugin-vue-define-options/vite'
  plugins: [
    DefineOptions(),
  ],

use:
<script lang="ts" setup>
defineOptions({
  name: 'xxx-xxxx',
})
</script>

**Comment by sxzz** [comment]
Reproduction please.

**Comment by coderkpc** [comment]
in src\env.d.ts
`import type { defineOptions } from 'unplugin-vue-define-options/vite';`

**Comment by Greasen** [comment]
> 

模块 ""unplugin-vue-define-options/vite"" 没有导出的成员 "defineOptions"。你是想改用 "import defineOptions from "unplugin-vue-define-options/vite"" 吗?

**Comment by Greasen** [comment]
> 

import type defineOptions from 'unplugin-vue-define-options/vite'
export type DefineOptions = typeof defineOptions
？
