### ISSUE TITLE
How to get rid of "Cannot find name defineOptions" error

### ISSUE THREAD

**Issue by teena-dot-dev** [sxzz/unplugin-vue-define-options#5]
Not a issue per se, but everywhere I use the `defineOptions`, I get this error:
`Cannot find name defineOptions`?
Is there a way to turn this off, or it has to do something with configuration?
I might have missed something in the docs

I'm using it alongside @innocenzi's [laravel-vite package](https://github.com/innocenzi/laravel-vite) and:
* unplugin-vue-define-options: ^0.3.1
* vite: ^2.8.3
* vite-plugin-laravel: ^0.2.0-beta.6
* @vitejs/plugin-vue: ^1.9.2
* Node version: v16.14.0
* VS Code
* WSL 2

When I click on the Quick fix by vscode, it generates this function:
```js
// 🤯
function defineOptions(arg0: {
  layout: import("vue").DefineComponent < {},{},{},{},{},
  import("vue").ComponentOptionsMixin,
  import("vue").ComponentOptionsMixin,
  import("vue").EmitsOptions,
  string,
  import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps,
  Readonly < ... > ,
  {} > ;
}) {
  throw new Error("Function not implemented.");
}
```

This is my `vite.config.ts`
```js
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import DefineOptions from "unplugin-vue-define-options/vite";
import laravel from "vite-plugin-laravel";
import { resolve } from "path";

export default defineConfig({
    plugins: [vue(), laravel(), DefineOptions()],
    resolve: {
        alias: {
            "@": resolve(__dirname, "./resources/ts"),
        },
    },
});
```

Thanks.

**Comment by innocenzi** [comment]
Hey, I think you just need to add `unplugin-vue-define-options` to your `tsconfig.json`'s `types` property

**Comment by teena-dot-dev** [comment]
> Hey, I think you just need to add `unplugin-vue-define-options` to your `tsconfig.json`'s `types` property

Yes, this fixed it!
Thanks

**Comment by HassanZahirnia** [comment]
Any ideas for eslint's `'defineOptions' is not defined.` error ?

**Comment by innocenzi** [comment]
Add it to `globals` in `.eslintrc` 👍
